//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppClient1.sr_MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="My fisrt Web ServiceSoap", Namespace="Web Services", ConfigurationName="sr_MyService.MyfisrtWebServiceSoap")]
    public interface MyfisrtWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace Web Services is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/HelloWorld", ReplyAction="*")]
        ConsoleAppClient1.sr_MyService.HelloWorldResponse HelloWorld(ConsoleAppClient1.sr_MyService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppClient1.sr_MyService.HelloWorldResponse> HelloWorldAsync(ConsoleAppClient1.sr_MyService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="Web Services/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="Web Services", Order=0)]
        public ConsoleAppClient1.sr_MyService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleAppClient1.sr_MyService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="Web Services", Order=0)]
        public ConsoleAppClient1.sr_MyService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleAppClient1.sr_MyService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Web Services")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyfisrtWebServiceSoapChannel : ConsoleAppClient1.sr_MyService.MyfisrtWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyfisrtWebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleAppClient1.sr_MyService.MyfisrtWebServiceSoap>, ConsoleAppClient1.sr_MyService.MyfisrtWebServiceSoap {
        
        public MyfisrtWebServiceSoapClient() {
        }
        
        public MyfisrtWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyfisrtWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyfisrtWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyfisrtWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppClient1.sr_MyService.HelloWorldResponse ConsoleAppClient1.sr_MyService.MyfisrtWebServiceSoap.HelloWorld(ConsoleAppClient1.sr_MyService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleAppClient1.sr_MyService.HelloWorldRequest inValue = new ConsoleAppClient1.sr_MyService.HelloWorldRequest();
            inValue.Body = new ConsoleAppClient1.sr_MyService.HelloWorldRequestBody();
            ConsoleAppClient1.sr_MyService.HelloWorldResponse retVal = ((ConsoleAppClient1.sr_MyService.MyfisrtWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppClient1.sr_MyService.HelloWorldResponse> ConsoleAppClient1.sr_MyService.MyfisrtWebServiceSoap.HelloWorldAsync(ConsoleAppClient1.sr_MyService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppClient1.sr_MyService.HelloWorldResponse> HelloWorldAsync() {
            ConsoleAppClient1.sr_MyService.HelloWorldRequest inValue = new ConsoleAppClient1.sr_MyService.HelloWorldRequest();
            inValue.Body = new ConsoleAppClient1.sr_MyService.HelloWorldRequestBody();
            return ((ConsoleAppClient1.sr_MyService.MyfisrtWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
    }
}
